---
title: '2019-11-05'
author: "Andy Price"
date: "11/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(infer)
library(moderndive)
library(tidyverse)
library(broom)

```

```{r}

lm.obj <- lm(score ~ age + gender, data = evals)

get_regression_table(lm.obj)

set.seed(10)

confidence_interval_evals <- evals %>%
  specify(response = age) %>%
  generate(
    reps = 1000,
    type = "bootstrap"
  ) %>%
  calculate(stat = "mean") %>%
  get_confidence_interval(level = 0.95, type = "percentile")


# pluck, ungroup, quantile tools

bootstrap <- evals %>% 
  rep_sample_n(size = 463, replace = TRUE, reps = 100) %>%
  group_by(replicate) %>%
  nest() %>%
  mutate(model = map(data, ~lm(score ~ age + gender, data = .x))) %>%
  mutate(age_coeff = map(model, ~tidy(.x))) %>%
  unnest(age_coeff) %>%
  filter(term == "age") %>%
  ungroup(replicate) %>%
  summarize(mean = mean(estimate),
            p.025 = quantile(estimate, probs = c(0.025)),
            p.975 = quantile(estimate, probs = c(0.975)))

  
#coeffe

#bootstrap


```

